/*
 * Distributed under the OSI-approved Apache License, Version 2.0.  See
 * accompanying file Copyright.txt for details.
 *
 * BP4Base.cpp
 *
 *  Created on: Sep 12, 2019
 *      Author: William F Godoy godoywf@ornl.gov
 */

#include "BP4Base.h"

#include "adios2/helper/adiosFunctions.h"

namespace adios2
{
namespace format
{

std::string BP4Base::MetadataName(const std::string &name) const noexcept
{
    const std::string bpName = helper::RemoveTrailingSeparator(name);
    // global metadata file is generated by rank 0
    /* the name of the metadata file is "md.0" */
    const std::string bpMetaDataRankName(bpName + PathSeparator + "md.0");
    return bpMetaDataRankName;
}

std::string BP4Base::DataName(const std::string &name, const size_t id,
                              const bool hasSubStreams) const noexcept
{
    const std::string bpName = helper::RemoveTrailingSeparator(name);
    const size_t index =
        m_Aggregator.m_IsActive ? m_Aggregator.m_SubStreamIndex : id;

    /* the name of a data file starts with "data." */
    const std::string bpRankName(bpName + PathSeparator + "data." +
                                 std::to_string(index));
    return bpRankName;
}

std::string BP4Base::BaseName(const std::string &name) const noexcept
{
    return helper::RemoveTrailingSeparator(name);
}

} // end namespace format
} // end namespace adios2
